### ISSUE TITLE
tk-icons

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#10]
While implementing the tk-form-field's dropdown, I found there is a dependency on three icons.
 
The icons are up-caret, down-caret and checkmark.

<img width="241" alt="screen shot 2016-12-23 at 2 33 30 pm" src="https://cloud.githubusercontent.com/assets/3114629/21461081/35df9816-c91c-11e6-9513-6a30c23f6456.png">

<img width="263" alt="screen shot 2016-12-23 at 2 20 42 pm" src="https://cloud.githubusercontent.com/assets/3114629/21461068/1c561cd0-c91c-11e6-8eff-9397014a8939.png">

As part of the effort to port the dropdown from xogroup/tk-form-fields (#9) we should port over the icon styles from [sharedweb/tk-icons](https://git.xogrp.com/sharedweb/tk-icons/tree/new)

**Comment by pkelly** [comment]
@rutu9 and @catarinatsang are working on new icons for Union as part of the foundational elements. In the meantime we could port over a slimmed down version.

**Comment by pkelly** [comment]
I created a new icon set for Guest Services that @mlonsdale designed that we might be able to use as a starting point.
https://git.xogrp.com/GuestServices/glm-icons

**Comment by jazzcrazed** [comment]
Might I suggest that the up/down/left/right carets be just a single icon that in CSS is rotated accordingly?

**Comment by silviatc** [comment]
New issue for creating new Union icons: https://github.com/xogroup/union/issues/42
