### ISSUE TITLE
Documentation for grid system

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#103]
As a developer interested in using the Union grid system
When I visit` docs.union.theknot.com/pattern-library/core-components/grid`
Then I should technical documentation for using the Union grid system

Requirements:
- Should include installation instructions for `@xo-union/bootstrap`
- Should point out that grid module is in `@xo-union/bootstrap/grid`
- Should include examples (Take examples or reference examples from [bootstrap](https://v4-alpha.getbootstrap.com/layout/grid/))

**Comment by smanwaring** [comment]
Can we mark this as complete?

**Comment by GeorgeTaveras1231** [comment]
@smanwaring Yes we can!
