### ISSUE TITLE
Remove 'general-' from icon names

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#110]
Requirements:
- [x] Update [this file](https://github.com/xogroup/union/blob/master/pattern-library/assets/icons/union-icons.svg) with new names
- [x] Update class names in [this file](https://github.com/xogroup/union/blob/master/pattern-library/src/icons/css/index.css)

**Comment by Jacfem** [comment]
https://github.com/xogroup/union/pull/112

**Comment by nycdavid** [comment]
@Jacfem @GeorgeTaveras1231 Can this issue be closed after the above merge?

**Comment by GeorgeTaveras1231** [comment]
Yup!
