### ISSUE TITLE
Add process documentation

### ISSUE THREAD

**Issue by silviatc** [xogroup/union#120]
As a Union user
I want to have documentation for how to contribute to patterns
So that it's clear what steps I need to take alone or with my collaborators on making a pattern

Given that I'm a Union user
When I go to the [wiki](https://github.com/xogroup/union/wiki/Union-Process-Documentation)
Then I know the process for identifying a pattern need -> seeing it live in documentation

Info:
example flows to consider:
- identifying a pattern need -> UI design -> UX documentation -> where to document it
- identifying a pattern change -> how to add the story to [issues](https://github.com/xogroup/union/issues)

**Comment by dmitrinesterenko** [comment]
Until we can start pulling from union we are trying to streamline the design process in terms of updating new designs. Need clarity around documenting things, when to do it and how to notify people at the right time. 

Two ways a) work with your squad engineers to introduce a new pattern or b) create a github issue: these end up being not prioritized and only get attention from volunteers a few times a week. 

Answer a) Being more proactive.

**Comment by GeorgeTaveras1231** [comment]
@dmitrinesterenko are there any updates on this effort?

**Comment by dmitrinesterenko** [comment]
@GeorgeTaveras1231 the [Wiki is here](https://github.com/xogroup/union/wiki/Union-Process-For-Design) and there is also a presentation that Rosina had put together.
