### ISSUE TITLE
Component Request - Datepicker 

### ISSUE THREAD

**Issue by marioharper** [xogroup/union#205]
New Component Request
===

## Description
There should be a `Datepicker` component in `@xo-union/tk-component-fields`. The Knot uses datepickers on multiple forms.

### Vendor Storefront
![screen shot 2017-07-21 at 10 23 32 am](https://user-images.githubusercontent.com/7682104/28470236-c1b462e0-6dfe-11e7-981c-28ceb51e3e2b.png)

### Vendor Request For Quote Form
![screen shot 2017-07-21 at 10 23 44 am](https://user-images.githubusercontent.com/7682104/28470243-c57b24cc-6dfe-11e7-957e-00cc79efffb3.png)

**Comment by GeorgeTaveras1231** [comment]
Timeline: Thurday 27th, July

**Comment by Samueljoli** [comment]
@marioharper @hsbacot is this in progress?

Apologies up front if your having to repeat this, ( maybe this was discussed in slack :man_shrugging: ) but whats the significance of `Timeline: Thurday 27th, July` @GeorgeTaveras1231 ?

**Comment by hsbacot** [comment]
Yes, it's in Progress. It's not Friday just yet @Samueljoli

**Comment by marioharper** [comment]
@Samueljoli you weren't in that meeting, but we had a meeting where we assigned DRI's to each component request we had at the time. The `Timeline: Thurday 27th, July` was the DRI's estimated time to submit a PR for the given component.

**Comment by Samueljoli** [comment]
@hsbacot @marioharper Ahh I see, thanks. Haha sorry about literally blowing up your issues with comments.

**Comment by hsbacot** [comment]
#228 I've opened a ticker for including external css files within our docs. Currently they don't appear to be supported and this is a requirement for the datepicker component to work. There are a few options to solve this. 

1. Allow an external stylesheet to be imported within our docs.
2. Create docs that don't depend on an interactive demo.
3. Host an interactive demo elsewhere

I'm for whichever is best for having this resolved asap. Any thoughts?

**Comment by hsbacot** [comment]
<img width="367" alt="screen shot 2017-07-27 at 11 35 53 pm" src="https://user-images.githubusercontent.com/1270494/28701487-881f5f6e-7324-11e7-9888-142c74482b41.png">

Current implementation

**Comment by marioharper** [comment]
@hsbacot what external css files are you trying to include? If you need to import them for them to work on the demo is it safe to assume each consumer would need to import them as well? Is there any way to make it so that datepicker doesn't rely on external styles?

**Comment by hsbacot** [comment]
We'd need to import the base react-date styles since they use a BEM convention in the base styles for the component.

https://github.com/airbnb/react-dates#webpack

They're namespaced and concies, however I can see how that might not be an option for everyone.

**Comment by marioharper** [comment]
@GeorgeTaveras1231 is there a way to tackle this? Using a library that requires global styles like this?

**Comment by marioharper** [comment]
@GeorgeTaveras1231 bump

**Comment by GeorgeTaveras1231** [comment]
@marioharper Thanks for the bump. There should be a way to require global styles using `a-css-loader`'s local or global mode. [here](https://github.com/xogroup/union/blob/master/webpack/css-rules.js#L12-L22) we target two files (using the `include` option) to be processed using `local` mode. You may be able to add the new file to that list so that it is processed correctly.

@hsbacot Let me know if this is helpful. I'd be happy to pair on this if necessary.

Side note: This method of targeting css for global processing is a bit brittle. I worked on a webpack config (in a separate project) that allows you to do the following, which I think is a more maintainable approach, just haven't had the time to implement in this project.

```javascript
import './path-to-my-global-css.scss?global'; // Note the query string
```

**Comment by hsbacot** [comment]
@GeorgeTaveras1231 Let's pair. I was hoping to be able to do this in the documentation for the component rather than include across all of the union docs

**Comment by marioharper** [comment]
For posterity, this was solved by wrapping the component in a css module class. Then, within that css module class, nest the global import of the external css library. This resulted in the external css library being scoped to only this component. 

```
.component-wrapper {
  :global {
    @import '~react-dates/lib/css/_datepicker'; // or any external css
    // any overrides to external css here
  }
}
```
