### ISSUE TITLE
Component Request - RadioButton

### ISSUE THREAD

**Issue by marioharper** [xogroup/union#206]
New Component Request
===

## Description
There should be a `RadioButton` component in `@xo-union/tk-component-fields`. The Knot uses radio buttons on multiple forms.

### Vendor Request For Quote Form
![screen shot 2017-07-21 at 10 33 04 am](https://user-images.githubusercontent.com/7682104/28470655-00d6fae0-6e00-11e7-8b73-56b0b8db5670.png)

**_Update_** 7/25/17
After discussion with two designers (Tyler & Rosina), we will be going with the design @peterkle commented with as the default radio button Union style : 

<img width="242" alt="screen shot 2017-07-25 at 9 24 08 am" src="https://user-images.githubusercontent.com/7682104/28576992-0d36a696-711b-11e7-89a4-a4b9667d1486.png">

**Comment by peterkle** [comment]
Guest List Manager onboarding uses a slight different styling:

![screen shot 2017-07-21 at 4 13 47 pm](https://user-images.githubusercontent.com/486241/28480641-a559d388-6e2f-11e7-9f21-36ecf84bf11f.png)

**Comment by marioharper** [comment]
Timeline: Friday 28th, July

**Comment by marioharper** [comment]
After discussion with two designers (Tyler & Rosina), we will be going with the design @peterkle commented with : 

<img width="242" alt="screen shot 2017-07-25 at 9 24 08 am" src="https://user-images.githubusercontent.com/7682104/28576992-0d36a696-711b-11e7-89a4-a4b9667d1486.png">

**Comment by tcmmct** [comment]
I'm discussing this in Unification Guild today. Will get final design decision this afternoon.

**Comment by marioharper** [comment]
@tcmmct what color should the background of the check icon be? Should it stay white? Or should it be the same as whatever color is behind it. 

![jul-25-2017 15-26-19](https://user-images.githubusercontent.com/7682104/28592127-a9e4ceaa-714d-11e7-920a-a4939dcbeab3.gif)

**Comment by tcmmct** [comment]
#FFFFFF Please
