### ISSUE TITLE
Component Request - Checkbox

### ISSUE THREAD

**Issue by marioharper** [xogroup/union#207]
New Component Request
===

## Description
There should be a `Checkbox` component in `@xo-union/tk-component-fields`. The Knot uses check boxes on multiple forms.

### Vendor Request For Quote Form
![screen shot 2017-07-21 at 10 31 52 am](https://user-images.githubusercontent.com/7682104/28470615-d91ddbf4-6dff-11e7-8435-a16b9ab3c6e4.png)

**Comment by marioharper** [comment]
Timeline: Friday 28th, July

**Comment by Samueljoli** [comment]
@robhorrigan are you currently working on this?

**Comment by robhorrigan** [comment]
@Samueljoli Haven't started yet but hoping to take a look sometime today

**Comment by marioharper** [comment]
@robhorrigan how is this coming along? I'd like to get a PR submitted by EOD if possible. Either I or @Samueljoli can assist if you have other things on your plate.

**Comment by robhorrigan** [comment]
Updated Checkbox design from Tyler Manhart:
![checkboxes](https://user-images.githubusercontent.com/4959203/28735719-262db6e2-73ac-11e7-82b7-eaff134483d4.png)
