### ISSUE TITLE
Component Request - ProgressBar

### ISSUE THREAD

**Issue by marioharper** [xogroup/union#208]
New Component Request
===

## Description
There should be a `ProgressBar` component. I currently know of one location where a progress bar is being utilized (Vendor Request For Quote Form).

### Vendor Request For Quote Form
![screen shot 2017-07-21 at 10 37 43 am](https://user-images.githubusercontent.com/7682104/28470850-aaec5264-6e00-11e7-9b5c-9fd054016afe.png)

**Comment by peterkle** [comment]
Guest List Manager onboarding:

![screen shot 2017-07-21 at 4 11 13 pm](https://user-images.githubusercontent.com/486241/28480582-53cffea2-6e2f-11e7-91f2-7b8c97bed2f1.png)

**Comment by Samueljoli** [comment]
@marioharper @GeorgeTaveras1231 @hsbacot Is anyone working on this?  I'd like to pick it up if someone hasn't.

**Comment by marioharper** [comment]
@Samueljoli I believe @hsbacot is to open a PR for this with just his migrated code from the Acquisitions squad implementation. Unless @hsbacot you'd like to assign @Samueljoli as DRI.

**Comment by Samueljoli** [comment]
@marioharper Ahh I see, does it make sense to add the `in-progress` label?

**Comment by marioharper** [comment]
Blocked until design decides on a generic progress bar design.

**Comment by GeorgeTaveras1231** [comment]
@marioharper @peterkle are there any other differences besides the colors used? I feel that development on this doesn't need to be blocked, the color could be left up to the consumer to specify, and we can plan to make the component more strict in the future if it makes sense.

**Comment by marioharper** [comment]
@GeorgeTaveras1231 Overriding the color and styles defeats the purpose of Union, right? I mean we could add those overrides but the underlying problem is that there is no definitive Union progress bar design.

**Comment by GeorgeTaveras1231** [comment]
@marioharper I agree but I don't think it should block developement and release of the progress bar. The system is not perfect and there are other examples of that besides this discrepancy, but when we run into these issues, we should try and be 'agile' about it. We can always iterate to make the component more restrictive in the future.

**Comment by hsbacot** [comment]
@marioharper @GeorgeTaveras1231 I agree that we shouldn't deviate from union, but we should always provide a way for the consumer to override if necessary. There is no harm by providing that freedom and without it, union would have to manage every edge case that comes up instead of the consumer.

**Comment by marioharper** [comment]
@hsbacot @GeorgeTaveras1231 I'm cool with adding overrides, I just wanted a clear stamp of approval from design of what the progress bar should look like / function without overrides. 

Speaking of overrides -- how do we want to implement overrides? Usually libraries have a `className` prop they open up and attach onto the root element, however, with CSS modules for someone to override the color of the progress bar they'd have to do something like: 
```
// .css
.my-override-class {
  .progress-98sJ928 { // this is the problem
     background-color: green;
  }
}

-----------

// .jsx
<ProgressBar className="my-override-class" />
```

And if we did something like : 
```
<ProgressBar color="green" />
```

That could get out of hand if you need to override other styles, right?

**Comment by GeorgeTaveras1231** [comment]
@marioharper One way to approach this is the use the css module object as the contract between the css and the component and allow the component to receive a different css module object with the same class identifiers but pointing to different classes. This is a known method for theming components with css modules.

https://github.com/css-modules/css-modules/blob/master/docs/theming.md

**Comment by GeorgeTaveras1231** [comment]
@marioharper it also doesn't need to be thought of as an override. We could publish ProgressBar1 and ProgressBar2 as the two standards and then delete the bad one when design makes a decision.
