### ISSUE TITLE
Component Request - Multi-step form

### ISSUE THREAD

**Issue by peterkle** [xogroup/union#213]
For Guest List Manager onboarding sequence, I am building a multi-step form component which has no presentational aspect, but rather manages state. It will leverage the Fullscreen Component #201 and several other form-related components not yet build.

![screen shot 2017-07-21 at 6 14 05 pm](https://user-images.githubusercontent.com/486241/28484448-6a11ab3c-6e40-11e7-9e6e-f63dd18aaaa8.png)
![screen shot 2017-07-21 at 6 04 56 pm](https://user-images.githubusercontent.com/486241/28484288-7b0fee54-6e3f-11e7-8e18-71f0164ad08e.png)
![screen shot 2017-07-21 at 6 05 00 pm](https://user-images.githubusercontent.com/486241/28484286-7b0d9726-6e3f-11e7-9c20-ea86c7af94a7.png)

**Comment by hsbacot** [comment]
Is there a reason we need to build this into a shared abstraction component? Managing the state of an application feels like it should be the applications job.

**Comment by peterkle** [comment]
I expressed this concern with @GeorgeTaveras1231 regarding how much of the onboarding code to contribute, and he suggested to share state management and UI because it would reduce duplicative effort.

**Comment by peterkle** [comment]
Discussed with @hsbacot after our meeting today. We decided it would be best in the long run to be  state mgmt agnostic in order be as flexible as possible. Closing this issue.

**Comment by peterkle** [comment]
comments anyone? I closed the PR.
