### ISSUE TITLE
Component Request - Inline text field

### ISSUE THREAD

**Issue by pkelly** [xogroup/union#216]
Guest Services is working on an on-boarding flow that is essentially the same as the one acquisition has built.

A large inline-text field is a requirement for that flow (see below). Having this field be shared between the flows would be fantastic so that we can leverage the great work that has already been done by acquisition.

<img width="1008" alt="screen shot 2017-07-24 at 11 54 11 am" src="https://user-images.githubusercontent.com/44373/28532300-70ca6c2e-7067-11e7-8b36-de6176e096bd.png">

**Comment by pkelly** [comment]
I've done work on this reflected in #202, however I'm holding off until we have our discussion to decide which teams are working on which components.

**Comment by pkelly** [comment]
Based on the convo today I'm forging ahead!

**Comment by pkelly** [comment]
This is now on PR #220 so that it can be packaged together with the Fancy Dropdown that @jmsardina is working on.

**Comment by Samueljoli** [comment]
@pkelly ah man this one is taken as well :(, would it make sense to add the `in-progress` label seeing that this seems to be in pr-state

**Comment by GeorgeTaveras1231** [comment]
Closing per #220
