### ISSUE TITLE
Component Request - Fancy Dropdown Component

### ISSUE THREAD

**Issue by jmsardina** [xogroup/union#218]
Guest Services is working on an on-boarding flow, which includes a dropdown menu that's stylistically different from the form dropdown.

<img width="216" alt="screen shot 2017-07-25 at 9 41 37 am" src="https://user-images.githubusercontent.com/10458903/28577871-951096d8-711d-11e7-80b6-6ffedfbedcfe.png">

**Comment by marioharper** [comment]
@jmsardina this looks like the one on the Acquisition squads onboarding process as well. 
<img width="1070" alt="screen shot 2017-07-25 at 1 40 11 pm" src="https://user-images.githubusercontent.com/7682104/28588075-e44a5484-713e-11e7-89d3-fd5f948a9737.png">

I'll send you a link to that code in slack. (In case you haven't already implemented this)

**Comment by Samueljoli** [comment]
@jmsardina Hey it seems like your in progress with this component. We should probably add the `in-progress` label, I can't seem to find any components to work on :(, you guys / gals are quick!

**Comment by GeorgeTaveras1231** [comment]
Closing per #220
