### ISSUE TITLE
Patternize Segment Events where logical

### ISSUE THREAD

**Issue by apattonXOXO** [xogroup/union#22]
Had a conversation with Rosina about the plans for the left rail navigation and it sounded like that might be a good opportunity to include the Segment event along with the pattern. The idea is that if the team uses that pattern correctly they won't need to implement separate tracking events, the pattern will have enough information to fire the event. Not exactly sure how this would work, but could potentially save a bunch of tech effort and would ensure data consistency across our products. Pull me over to discuss whenever!

**Comment by silviatc** [comment]
From Federation meeting:

- requires more consideration
- might not be the best to open source
- doesn't feel like a 1.0 item. Will discuss after first delivery.
