### ISSUE TITLE
External Style dependency in docs

### ISSUE THREAD

**Issue by hsbacot** [xogroup/union#228]
Context
===

- [x] Visual bug?
- [ ] Runtime bug?
- [ ] Build bug?

### *package name(s) and versions*

`tk-datepicker`

### *javascript runtime*
> If browser, browser name and version. If node, node version:

Issue
===

### What are you trying to achieve or the steps to reproduce ?
Unable to include a necessary stylesheet on the corresponding documentation page.

### What result did you expect ?
We're expecting to be able to demo the component with similar appearance to how it will appear in an application.

### What result did you observe ?
External stylesheets are restricted from being loaded in the docs. This results in an unstyled datepicker component

**Comment by GeorgeTaveras1231** [comment]
@marioharper Are you ok with documenting your approach to adding global styles?

**Comment by marioharper** [comment]
@GeorgeTaveras1231 yeah, no problem. Where would you like this to live? In the FAQ of the wiki?

**Comment by GeorgeTaveras1231** [comment]
@marioharper Yea that seems fine.

**Comment by GeorgeTaveras1231** [comment]
Closing this per the addition to our FAQ

https://github.com/xogroup/union/wiki/FAQ
