### ISSUE TITLE
Standard test variables

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#235]
Our current strategy for defining test variables is to use scope `let` variables. 

For example

```javascript
describe('description', () => {
  let var1;

  beforeEach(() => {
     var1 = 'Define value for each test';
  });

  it('works', () => {
    expect(var1).toBe('Define value for each test');
  });
});
```

However, this is a bad practice according to [this lint rule](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/docs/rules/no-describe-variables.md).

Should we maintain this method of defining variables or should we adhere to the best practices described by that rule?

**Comment by marioharper** [comment]
Interesting, I'm fine with it if it's a best practice with Jasmine. Something to look for now with incoming PRs.

**Comment by GeorgeTaveras1231** [comment]
@marioharper well we can enable that lint rule so it will be automatically checked for us. 😄

**Comment by hsbacot** [comment]
I'm for migrating to follow since our current implementation  can cause
memory leaks 👍

**Comment by GeorgeTaveras1231** [comment]
Cool, is this enough to close this issue? Thinking about adding another issue to request this change.

**Comment by marioharper** [comment]
Yeah, I think this is enough to close this. I agree, a chore issue for someone to pickup during hack time or something would be good.
