### ISSUE TITLE
localStorage.setItem causing onboarding to break in private Safari windows on production

### ISSUE THREAD

**Issue by sgottfried** [xogroup/union#242]
Context
===

- [x] Visual bug?
- [x] Runtime bug?
- [ ] Build bug?

### *package name(s) and versions*
`tk-component-icons` version 0.43

### *javascript runtime*
> If browser, browser name and version. If node, node version:

Mobile Safari 
iOS version 10.3.3.

Issue
===

### What are you trying to achieve or the steps to reproduce ?

Go to https://www.theknot.com/.
Click on Sign Up button.

### What result did you expect ?

Expected to see the onboarding flow names and roles step.

![image](https://user-images.githubusercontent.com/821288/28845946-a9f16d74-76d7-11e7-9a56-370ca26e6264.png)

### What result did you observe ?

Instead, a blank screen appeared:

![image](https://user-images.githubusercontent.com/821288/28845982-c96e8222-76d7-11e7-8a13-7ad2dbd5bd34.png)

I found this error in the console: 

![image](https://user-images.githubusercontent.com/821288/28846028-ec99f830-76d7-11e7-984c-ef32a7bf7f72.png)

and traced it to this code in this package:

![image](https://user-images.githubusercontent.com/821288/28846040-fbddd910-76d7-11e7-81b8-5224fed78757.png)

We have our own polyfill which overrides localStorage, but it is being called after the offending line: https://git.xogrp.com/Acquisition/tk-onboarding-rails/blob/develop/client/app/utils/index.js#L29

**Comment by GeorgeTaveras1231** [comment]
I image a simple try catch around this line should fix the issue: 

https://github.com/xogroup/union/blob/master/packages/%40xo-union/tk-component-icons/src/assets/setup/index.js#L55

**Comment by sgottfried** [comment]
@GeorgeTaveras1231 Ok, I can make a PR for that. It looks like I need to be added to this project first.

**Comment by hsbacot** [comment]
@sgottfried You should be able to create a fork and submit a pull request from your forked branch.

**Comment by sgottfried** [comment]
@hsbacot Ah right, thanks

**Comment by GeorgeTaveras1231** [comment]
Closing per #247
