### ISSUE TITLE
Button - Naming Convention for Button Size Classes

### ISSUE THREAD

**Issue by madelinehvu** [xogroup/union#253]
Change naming convention for button size classes to reflect, "small, medium, large"

baby = small
mama = medium
papa = large

Documentation will be changed in GUI kit in Sketch as well

**Comment by GeorgeTaveras1231** [comment]
@madelinehvu I added a `blocked: sync w/ design ui kit` label to denote that his work needs to be synchronized. Can you be the DRI to unblock this when the design ui kit is updated?

**Comment by madelinehvu** [comment]
@GeorgeTaveras1231 for sure. I updated the GUI kit yesterday so I will unblock!

**Comment by GeorgeTaveras1231** [comment]
Oh cool. Thank you 😄
