### ISSUE TITLE
Dropdown components behavior standardization 

### ISSUE THREAD

**Issue by smanwaring** [xogroup/union#268]
Context
===
We have several dropdown components that I noticed have slightly different behaviors. I think we should standardize the base dropdown behavior for consistency.

**Specifically:**
- Dropdown should close when a list-item is selected, but should it close when the main input area is selected (i.e., user doesn't select any list-item and just clicks on the main dropdown field)?

Is there anything else that we should standardize for dropdown list behavior?

This will need design review.

**Comment by cbirrell** [comment]
"Dropdown should close when a list-item is selected, but should it close when the main input area is selected (i.e., user doesn't select any list-item and just clicks on the main dropdown field)?" 

Yes, it should close when the user clicks again unless the dropdown is a multi-select dropdown.  

This is only true if it is a form-field dropdown (user selects something to submit).  This is not if it is a list dropdown (think left navigation, for example).  @tcmmct 

Let me know if this makes sense?

**Comment by smanwaring** [comment]
@cbirrell Yes, that makes sense. I'll go ahead and update the components. We don't have any multi-select dropdowns at the moment. Thanks! 👍
