### ISSUE TITLE
MembershipModal "unknown prop 'validations' on <input>" error

### ISSUE THREAD

**Issue by peterkle** [xogroup/union#280]
Context
===

- [ ] Visual bug?
- [x] Runtime bug?
- [ ] Build bug?

### *package name(s) and versions*

`@xo-union/tk-component-membership-modal@0.1.0-0`

### *javascript runtime*

Chrome 60
node 6.11.1
react@15.6.1

Issue
===

I am consuming the membership modal like so:

```
<MembershipModal
  metadata={{ userAction: '', applicationName: '' }}
  openModal={this.state.openModal}
  onClickLogIn={this.openLogInModal}
  onClickSignUp={this.openSignUpModal}
  onClose={this.closeModal}
/>
```

When I first click to open the modal, I see the Log in form. All goes well. Then, if I click `Not a member yet? Join now!` inside the modal, I see the following error in the console:

![screen shot 2017-08-14 at 2 42 11 pm](https://user-images.githubusercontent.com/486241/29286335-af2ce534-80ff-11e7-8c22-98649571e673.png)

**Comment by GeorgeTaveras1231** [comment]
Thanks @peterkle. This should be addressed per changes in #278
