### ISSUE TITLE
Grid components API

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#281]
We have implemented the Column component which has the following API.

```jsx
<Column /> 
<Column xs="6" /> 
<Column sm /> 
<Column sm="6" /> 

/* Results in */

<div class="col" />
<div class="col-6" />
<div class="col-sm" />
<div class="col-sm-6" />
```

These are the proposed APIs for the additional grid components:

### Column (Missing order prop)

```jsx
<Column order="6" /> 

/* Results in */
<div class="order-6" >
```

```jsx
<Column orderSm="6" /> 

/* Results in */
<div class="order-sm-6" >
```

### Row

```jsx
<Row /> /* simple row */
<Row noGutters /> /* row without gutters */
```

### Container

```jsx
<Container /> /* simple container */
<Container fluid /> /* fluid container */
```

**Comment by hsbacot** [comment]
How will offsets be handled?

**Comment by marioharper** [comment]
should `noGutters` just be `gutters={false}` and default it to `true`?

**Comment by GeorgeTaveras1231** [comment]
@hsbacot TW Bootstrap deprecated offsets in the grid modules, So the will be handled with our spacing module. The `Column` components accepts `className` which will allow you to do:

```jsx
<Column className={spacing['ml-up-10']} />
<Column className={spacing['mx-auto']} /> /* Centered */
```

**Comment by hsbacot** [comment]
Is order referring to pull? I think that might be more intuitive since this is from bootstraps grid system.

**Comment by GeorgeTaveras1231** [comment]
@marioharper I thought of that since there isn't a reason for a consumer to ever pass `gutters={true}` I thought it made sense to use `noGutters` instead. It also resembles the actual tw bootstrap class that is used.

**Comment by GeorgeTaveras1231** [comment]
@hsbacot order is referring to the layout order defined by the `flex` property `order`. There are a set of classes to help 're-align' columns that are named `order-{breakpoint}-{1...12}`

**Comment by hsbacot** [comment]
I think this is solid 👍

**Comment by marioharper** [comment]
I agree, I think its a good and consistent implementation.

**Comment by smanwaring** [comment]
I think this is great 👍

**Comment by GeorgeTaveras1231** [comment]
Thanks guys for the feedback. Just a quick update on this:

We decided to remove the `xs: true` default API.

```jsx
<Column />
```

```html
<div class="col" />
```

That's because there are use cases for not using the `col` class while using some of the other breakpoint classes.

For example:

```jsx
<Column md="6" />
<Column md="6" />
```

Should render as:

```
On md breakpoint
|____________||____________|

On small breakpoint
|__________________________|
|__________________________|
```

Which doesn't work when the `col` class is assumed.

### Change

If consumers want to use the `col` class, they need to specify the `xs:true` prop

```jsx
<Column xs />
```

```html
<div class="col" />
```

Thanks @smanwaring for finding this out.
