### ISSUE TITLE
Membership SDK API

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#297]
The current version of the Membership SDK has the following API.

```js
import MembershipService, { MembershipClient } from '@xo-union/sdk-membership'

const isProduction = /* Left up to App developers to figure out */;
const apiKey = /* Left up to App developers to figure out */
const clientConfig = isProduction ? MembershipClient.presets.production : MembershipClient.presets.qa;

const service = new MembershipService({
  clientOptions: {
    config: {
      ...clientOptions,
      apiKey
    }
  }
});
```

## Problems

- MembershipClient is not exported (this is easy to fix )
- When consumers don't have direct access to the instantiation of the service, they cannot pass the API Key or customize where the requests are made to

## Proposal

- Allows consumers to configure service on instantiation
> This proposal is to provide flexibility to configure your own client however you want. Useful for edge cases or complex testing scenarios (For example, app level integration tests that use a mock server for membership)

```js
const service = new MembershipService({
  clientOptions: {
    env: 'qa',
    apiKey: 'my-api-key'
  }
})
```

- Use environment variables to customize all clients.
> This proposal is to provide a way to use a standard set of configurations for a whole application, regardless of whether or not you have control over the instantiation

### Front end app perspective
Front end apps will need to configure their webpack build to pass the membership environment variables to the build
```js
/* webpack.config.js */
module.exports = {
  plugins: [
    new webpack.EnvironmentPlugin(['UNION_MEMBERSHIP_ENV', 'UNION_MEMBERSHIP_HOST', 'UNION_MEMBERSHIP_API_KEY'])
  ]
}
```

```js
/* pseudo code internal to sdk */

const defaultHosts = {
  production: 'production-host',
  qa: 'qa-host'
};

class MebershipClient {
  constructor(config) {
    const membershipEnv = config.env || process.env.UNION_MEMBERSHIP_ENV || process.env.NODE_ENV;
    this.host = config.host || defaultHosts[membershipEnv].host || process.env.UNION_MEMBERSHIP_HOST;
    this.apiKey = config.apiKey || process.env.UNION_MEMBERSHIP_API_KEY;
  }
}
```

**Comment by marioharper** [comment]
I'm cool with adding support for env var configuration. Doesn't hurt to add additional ways to configure the service.

**Comment by GeorgeTaveras1231** [comment]
Thanks @marioharper and @hsbacot, I will close in favor of issue to implement this API. #305
