### ISSUE TITLE
Potentially missing documentation + generator improvements

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#30]
These are some things that came up from today's work session.

### Documentation
- System requirements
  - xcode
  - moxjpeg? (There was one instance where this dependency caused issues...Would like to learn how critical this is of if could be fixed by including xcode)

### Generators
- [ ] Make `name` question clearer: 'component name' instead of 'package name'
- [x] Clarify that conflict in `external-cssmodules.json` is a normal part of the generation process --  Addressed by #28

**Comment by pkelly** [comment]
As far as system requirements go I say we shouldn't worry too much about OS X older than 10.11 El Capitan.

**Comment by GeorgeTaveras1231** [comment]
@pkelly do you think we should document the xcode requirement? Part of me feels like it is too low-level and we should just focus on dependencies on node and the node ecosystem.

**Comment by pkelly** [comment]
@madelinehvu is on 10.11 and didn't run into the xcode requirement. So unless someone else proves otherwise I wouldn't worry about it.

**Comment by silviatc** [comment]
From Federation meeting:

- there's no way to simplify this more. If somebody looks through readme and finds a way, please open up a separate issue.
