### ISSUE TITLE
Code up the content of the Union Landing Page

### ISSUE THREAD

**Issue by pkelly** [xogroup/union#34]
Move existing Union pages into `/patterns`, linked from pattern library on landing page.

<img width="655" alt="screen shot 2017-01-30 at 3 03 33 pm" src="https://cloud.githubusercontent.com/assets/44373/22439413/859a4a50-e6fd-11e6-833e-cbe81acfbbf9.png">

**Comment by pkelly** [comment]
Un-assigning this for now cause the design has since changed and our current priority is on building components instead of Union doc layout.

**Comment by dmitrinesterenko** [comment]
Let's open a new issue with the new comps.
