### ISSUE TITLE
Update form-fields: typography, colors, and spacing

### ISSUE THREAD

**Issue by pkelly** [xogroup/union#37]
Update  `form-fields` react components to match https://github.com/xogroup/union-gui-kit/blob/master/core_components-forms.sketch

- [x] Border of invalid state should be same color as background (see screenshot 👇)
- [x] Replace `font-size-xsmall` with `font-down-4`
- [x] Use typography/sizes for all font-sizes
- [x] Migrate `_tk-colors.scss` to `colors/index.css`now that tk-colors is all up to date
- [x] Use @xo-union/colors for all colors
- [x] Remove `fields/css/shared/colors.css`
- [x] Possibly update spacing to be factors of 4px. Will need help from @rutu9 to make decisions on this one
- [x] Figure out why `-webkit-input-placeholder` for placeholder isn't working

![screen shot 2017-02-16 at 3 44 57 pm](https://cloud.githubusercontent.com/assets/44373/23040323/e7d5133a-f45e-11e6-89fe-9787a9380601.png)

**Comment by silviatc** [comment]
Make sure to also update colors for new error states (currently being explored by @rosinabosco)
