### ISSUE TITLE
Migrate Jekyll tk-colors

### ISSUE THREAD

**Issue by pkelly** [xogroup/union#44]
Make sure `core/colors` in React land matches updated vars in `css/_tk-colors` and convert to `@value` syntax

Optional: it would be nice to add a doc page for colors at  http://localhost:8080/foundations/buttons
Doesn't need to show all the colors since the format of this page isn't decided, but a few examples would be nice.
See the static mock on Jekyll as an example.
https://xogroup.github.io/union/foundations/colors/

**Comment by jazzcrazed** [comment]
@pkelly @silviatc Is the colors comp somewhere else we could look at? Lost track of it on the Jekyll URL.

**Comment by pkelly** [comment]
@jazzcrazed: I forked Union and rolled back to a working version of Jekyll you can reference.
https://pkelly.github.io/union/foundations/colors/

**Comment by pkelly** [comment]
The latest colors from Sketch have been added / updated so that `colors/index.css` is in sync with
https://github.com/xogroup/union-gui-kit/blob/master/core_components-color_palette.sketch

However, this Sketch file is still being worked on so there will be more changes later.
