### ISSUE TITLE
Decide on grid + column gutters

### ISSUE THREAD

**Issue by pkelly** [xogroup/union#46]
Current grid gutters are 15px on each side, and columns have default left and right padding of 15px.
http://v4-alpha.getbootstrap.com/layout/grid/#variables

Should we change this to be divisible by 4px to be consistent with our spacing system? Is there a good reason why Bootstrap uses 15 by default? Does it impact the 12 col system?

**Comment by jazzcrazed** [comment]
@pkelly @silviatc I would vote going with the bootstrap default. Grids are a rather mature system nowadays, and it's arguably not worth substantially customizing them as the effort outweighs the user impact.

**Comment by pkelly** [comment]
I agree. I think there should be a really good reason to change these kinds of defaults.

**Comment by jameree** [comment]
@pkelly @jazzcrazed then would you say that we should move to 5px system? It could be weird if our grids are designed on multiple of x5 in some places then x4 in other ways.

**Comment by jameree** [comment]
So for example. If i adhered to 30px gutters here, but kept everything else multiples of 4, we'd have some weird spacing rules:
![screen shot 2017-02-09 at 3 13 31 pm](https://cloud.githubusercontent.com/assets/2028742/22801334/732aa01a-eeda-11e6-97fa-031005c15292.png)

**Comment by silviatc** [comment]
@jameree do you want to lead this exploration and I can help you? Just ping Mark about it and we can kick it off

**Comment by jameree** [comment]
@silviatc I'd be happy to!

**Comment by silviatc** [comment]
@GeorgeTaveras1231 just submitted a pull request for this (but I did get the error "Your tests failed on CircleCI"). What's our process again for pull request review and closing out issues?

**Comment by silviatc** [comment]
Reference links:
Grid calculations: https://docs.google.com/spreadsheets/d/18Hnn3V0fKX4bo5Xx897iMmGhncxJrOzXRdVNhuyHJYw/edit#gid=932413317
Invision prototypes: https://xogrp.invisionapp.com/share/YEAMWEBJ7

**Comment by silviatc** [comment]
Taken care of with this issue: https://github.com/xogroup/union/pull/94
