### ISSUE TITLE
Update Demo components to handle multiple classNames

### ISSUE THREAD

**Issue by pkelly** [xogroup/union#47]
When using the `<Demo />` component with a single class name
`<div className={type.tisaMed}>Tisa Medium (font-weight: 500)</div>`
the code example is correct, however with multiple classNames
```className={`${type.tisaMed} ${type.fontUp4}`}``` the compiled classnames are shown.
<img width="760" alt="screen shot 2017-02-09 at 5 19 27 pm" src="https://cloud.githubusercontent.com/assets/44373/22805974/de6ec7ee-eeed-11e6-9c71-e7843930aedc.png">

**Comment by GeorgeTaveras1231** [comment]
This is a good callout @pkelly. This should be simple to fix. Just handle a list of classes in this function:

https://github.com/xogroup/union/blob/master/packages/components/doc-utils/src/Demo/index.jsx#L29-L31

**Comment by GeorgeTaveras1231** [comment]
Closing this since this is harder than I initially expected + there isn't a consistent solution to this problem. In the meantime, we advice not to combine classes this way, but rather use `composes` in the documentation.
