### ISSUE TITLE
Update colors Sass file

### ISSUE THREAD

**Issue by silviatc** [xogroup/union#52]
From Catarina's last update to Sketch file in Folio, make the following changes:

- [x] Update values for alt blue
- [x] Add dark blue

**Comment by pkelly** [comment]
@silviatc: Since @rutu9 and I updated the colors last week for form fields I went ahead and updated them again based on Sketch (core_components-color_palette) just now.

Pretty sure we can close this out based on my latest PR https://github.com/xogroup/union/pull/72
