### ISSUE TITLE
Create interim color documentation

### ISSUE THREAD

**Issue by silviatc** [xogroup/union#53]
As a developer
I want to see the colors displayed in a color table (or other simple color display format)
So that I can see that all the colors are working

**Comment by jazzcrazed** [comment]
Blocked by #17

**Comment by jazzcrazed** [comment]
TODO:
- [ ] Handling the hyphenization; some weirdness happening.
- [ ] Integrate Silvia's comp once it's complete.

**Comment by GeorgeTaveras1231** [comment]
Closing this per what's available [here](http://docs.union.theknot.com/pattern-library/core-components/colors). We will have a separate set of sprints dedicated to improving the design of these documentation pages.
