### ISSUE TITLE
Add header to Union Landing Page

### ISSUE THREAD

**Issue by silviatc** [xogroup/union#57]

**Comment by pkelly** [comment]
@rutu9: Are the comps finalized for the new header? Could you add some specs here if so?

**Comment by rutu9** [comment]
@GeorgeTaveras1231 @pkelly zeplin link to headers https://zpl.io/1sfrMM

**Comment by GeorgeTaveras1231** [comment]
thanks @rutu9

**Comment by kwokster10** [comment]
@rutu9 could you add me to the zeplin project?

**Comment by dmitrinesterenko** [comment]
@GeorgeTaveras1231 this is an outdated design closing this feature as there is a header on the documentation and it can use improvement in separate detailed issues.
