### ISSUE TITLE
Update error state for form fields

### ISSUE THREAD

**Issue by silviatc** [xogroup/union#63]
As a form field user
I want to see an error state that isn't the same color as our main CTA
So that I will be able to easily distinguish between the error state and the CTA

**Comment by GeorgeTaveras1231** [comment]
@silviatc @catarinatsang What exactly is this referring to? Is this a duplicate of #70? Or could these issues be combined to have one issue related to fields?

**Comment by pkelly** [comment]
I created a new issue for all form field styling updates which includes this
#113
