### ISSUE TITLE
Adding alignment utility class

### ISSUE THREAD

**Issue by silviatc** [xogroup/union#7]
@pkelly I was thinking back to what was the most annoying to override when it came to typography, and alignment was definitely up there. There was no easy way (from the class name) to predict whether something would be left-aligned or centered.

I think it makes sense to introduce alignment as part of the utility classes required to style a component.

Also, lmk if issues was the right place for this... I'm just trying it out :)

**Comment by pkelly** [comment]
Yep, that makes sense. Bootstrap has text-alignment utility classes that I think will cover it for us.
http://v4-alpha.getbootstrap.com/utilities/typography/

**Comment by pkelly** [comment]
Closing this since Bootstrap should have all the utilities we need for alignment, including responsive helpers.
