### ISSUE TITLE
Date picker designs

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#8]
Are there any plans to re-design the date picker to look more like the new fields?

**Comment by GeorgeTaveras1231** [comment]
Did some research to see what we currently use and it seems we use a [this implimentation](http://jsfiddle.net/Eonasdan/0Ltv25o8/) with some custom styles

**Comment by pkelly** [comment]
This came up on Guest Services and they were gonna look into Airbnb's react date picker and see how customizable it is.
https://github.com/airbnb/react-dates

**Comment by pkelly** [comment]
Example of existing BS3 datepicker on dashboard
https://qa-beta.theknot.com/dashboard#/edit
