### ISSUE TITLE
First React component example, forms

### ISSUE THREAD

**Issue by ajbeach2** [xogroup/union#9]
I am referencing the discussions from the last federation meeting. The user story for this is as follows:

As a dev, I should have a react example for forms, based on the design mocks for forms.

**Comment by jazzcrazed** [comment]
@silviatc @pkelly For your reference. Please fill in details when you have the chance!

**Comment by pkelly** [comment]
Form elements are and running with the new React Union thanks to @GeorgeTaveras1231.

Based on the desc of this issue I'm calling this complete. We can open a new issue if we want to change the format of the documentation.

<img width="832" alt="screen shot 2017-01-25 at 3 32 25 pm" src="https://cloud.githubusercontent.com/assets/44373/22308099/92215e00-e313-11e6-9cc4-ac857775de48.png">
